server:
  port: 8080
  enable_print_routes: false
  read_timeout: 30s
  write_timeout: 30s
  limiter:
    max: 100
    expiration: 1m
  cross_origin_policy:
    corp: "cross-origin"
    cors_allow_origins: "*"
    cors_allow_methods: "GET,POST,PUT,DELETE,HEAD,OPTIONS"
    cors_allow_headers: "Origin,Content-Type,Accept,Authorization,Cache-Control,If-None-Match"

images:
  max_image_dimension: 8192 # 8k
  max_file_size_in_bytes: 52428800 # 50MB
  source: "local" # allowed values awss3, local
  awss3:
    bucket: ""
  local:
    base_path: "./delete_me/images"

templates:
  source: "local" # allowed values awss3, local
  awss3:
    bucket: ""
  local:
    base_path: "./delete_me/templates"

  default_font_path: "/usr/share/fonts/arial/ARIAL.TTF" # path to default font

experimental:
  enable_upload_api: false
